### ISSUE TITLE
bug in compilation with pip install

### ISSUE THREAD

**Issue by simondub** [cleemesser/python-edf#5]
on a system having numpy<2 installed, the command `pip install .`   fails. 

This is because there is conflicting information between pip (pyprojects.toml) and setup.py.

With pip>24.1.2, the command `pip install .` will install numpy>2 and the setup.py will use the local version numpy<2. 
The conflicting version of numpy will create an error.

The solution os probably to migrate the project totally to pip.
https://packaging.python.org/en/latest/guides/modernize-setup-py-project/

**Comment by cleemesser** [comment]
Thanks for the alert. It does look like the packaging needs some love. I should get to this sometime, as I cycle through code maintenance. I am focused on another EEG related project at the moment. 
I would also accept pull requests.

**Comment by cleemesser** [comment]
https://github.com/cleemesser/python-edf/pull/9 [from cleemesser/memviews](https://github.com/cleemesser/python-edf/commit/26f30fdaf0f31f72fbc16ec7a13ae17d72e6f885) now merged into master should resolve this issue as I have removed info from setup.py
